### ISSUE TITLE
gltf-asset-auditor gives error on build or running 

### ISSUE THREAD

**Issue by deep9888** [KhronosGroup/gltf-asset-auditor#3]
Hello,
I need to install gltf-asset-auditor using npm and need to integrate with threejs code. I installed this library by
`> npm i @khronosgroup/gltf-asset-auditor`
and import library like this -
`import { Auditor } from '@khronosgroup/gltf-asset-auditor';`
when I try to build my code, it gives me the following error-
![error](https://user-images.githubusercontent.com/103727216/226819789-bf37647a-180e-44dd-8afe-4fb35230afce.png)

Can someone guide me in this solving this error, and is there any tutorial or documentation for this?

**Comment by MikeFesta** [comment]
Your installation and import statements look correct. Can you confirm that the dist folder has been created?
```
node_modules/@khronosgroup/gltf-asset-auditor/dist
```
There should be 81 files generated files in there, including Auditor.d.ts / Auditor.js / Auditor.js.map.

If the folder and those files are not there, you can try to generate them by running npm run build from within the node_modules/@khronosgroup/gltf-asset-auditor folder.

**Comment by deep9888** [comment]
Yes, the dist folder exists, and in the dist folder, there are 81 files and Auditor.d.ts / Auditor.js / Auditor.js.map are also included.

**Comment by deep9888** [comment]
If I change the path as you give in web-example like this `import { Auditor } from '@khronosgroup/gltf-asset-auditor/dist/Auditor';` then it gives me a different error. 
![error1](https://user-images.githubusercontent.com/103727216/227115985-9f6a7d56-6d5d-4e40-bc4e-edf973fac01a.png)

**Comment by deep9888** [comment]
I have created a new test application. When I run that app using `npm run dev `, I get the following errors-
![error2](https://user-images.githubusercontent.com/103727216/227124734-5ba16a79-2f3f-4189-afe4-58dd602c08b8.png)
![error3](https://user-images.githubusercontent.com/103727216/227124739-af6424b8-beb2-402d-bed5-da48d34cb4e5.png)

**Comment by deep9888** [comment]
If I go inside `node_modules\@khronosgroup\gltf-asset-auditor` and run `npm run build` it gives me the following errors -

![error4](https://user-images.githubusercontent.com/103727216/227162616-f5f73778-6dea-4499-b41b-388c8a1c4bec.png)
![error5](https://user-images.githubusercontent.com/103727216/227162624-24eea05e-9170-4c00-bf91-04d6d97bc8cf.png)
![error6](https://user-images.githubusercontent.com/103727216/227162629-e83ee0eb-1c39-47ae-80e7-87a3ce216fff.png)

**Comment by deep9888** [comment]
It's working; the main issue was web pack configuration, so after spending 2 hours, I found I needed to add `path: false, fs: false`  in `webpack.common.js.` of my main project.

**Comment by MikeFesta** [comment]
I'm glad that you were able to get it running! Thanks for sharing your solution. 

I'll update the readme in the web-example to call out that configuration. There is a note in the web-example with those values, but it's not very obvious. https://github.com/KhronosGroup/gltf-asset-auditor/blob/main/web-example/webpack.config.js#L41

The reason that those values are needed is because the Asset Auditor was built to be used in both a Node.js environment as well as in a web browser and the fs (filesystem) and path modules are only available in Node.js. The frontend code doesn't call those functions, but the compiler (webpack) tries to link them anyway and setting them to false in the config allows for them to be ignored.
